#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'USAGE'
Usage:
  collect_v2d_regression_evidence.sh [options]

Options:
  --output <path>       Output env file path
                        default: docs/loadtest/evidence/v2d_regression.env
  --root <path>         Repo root path (default: git top-level or cwd)
  --skip-chat-test      Skip chat_test debate_mvp_signoff suite
  --skip-chat-server    Skip chat_server nextest suite
  --skip-notify-server  Skip notify_server nextest suite
  -h, --help            Show this help
USAGE
}

ROOT=""
OUTPUT=""
RUN_CHAT_TEST="true"
RUN_CHAT_SERVER="true"
RUN_NOTIFY_SERVER="true"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --output)
      OUTPUT="$2"
      shift 2
      ;;
    --root)
      ROOT="$2"
      shift 2
      ;;
    --skip-chat-test)
      RUN_CHAT_TEST="false"
      shift
      ;;
    --skip-chat-server)
      RUN_CHAT_SERVER="false"
      shift
      ;;
    --skip-notify-server)
      RUN_NOTIFY_SERVER="false"
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage
      exit 1
      ;;
  esac
done

if [[ -z "$ROOT" ]]; then
  if git rev-parse --show-toplevel >/dev/null 2>&1; then
    ROOT="$(git rev-parse --show-toplevel)"
  else
    ROOT="$(pwd)"
  fi
fi

if [[ -z "$OUTPUT" ]]; then
  OUTPUT="$ROOT/docs/loadtest/evidence/v2d_regression.env"
fi

mkdir -p "$(dirname "$OUTPUT")"

run_check() {
  local key="$1"
  shift
  if "$@"; then
    echo "$key=pass"
    return 0
  fi
  echo "$key=fail"
  return 0
}

{
  echo "# generated by collect_v2d_regression_evidence.sh"
  echo "REGRESSION_LAST_RUN_AT=$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
  echo "REGRESSION_GIT_HEAD=$(git -C "$ROOT" rev-parse --short HEAD 2>/dev/null || echo unknown)"

  if [[ "$RUN_CHAT_TEST" == "true" ]]; then
    run_check "REGRESSION_CHAT_TEST_DEBATE_MVP_SIGNOFF" \
      bash -lc "cd '$ROOT/chat' && cargo test -p chat_test debate_mvp_signoff -- --nocapture >/dev/null"
  else
    echo "REGRESSION_CHAT_TEST_DEBATE_MVP_SIGNOFF=skipped"
  fi

  if [[ "$RUN_CHAT_SERVER" == "true" ]]; then
    run_check "REGRESSION_CHAT_SERVER_NEXTEST" \
      bash -lc "cd '$ROOT/chat' && cargo nextest run -p chat-server --all-features --no-tests pass >/dev/null"
  else
    echo "REGRESSION_CHAT_SERVER_NEXTEST=skipped"
  fi

  if [[ "$RUN_NOTIFY_SERVER" == "true" ]]; then
    run_check "REGRESSION_NOTIFY_SERVER_NEXTEST" \
      bash -lc "cd '$ROOT/chat' && cargo nextest run -p notify-server --all-features --no-tests pass >/dev/null"
  else
    echo "REGRESSION_NOTIFY_SERVER_NEXTEST=skipped"
  fi
} >"$OUTPUT"

echo "regression evidence written: $OUTPUT"
