-- merged into baseline users schema (20240426045903_initial.sql):
-- 1) email nullable
-- 2) phone_e164 / phone_verified_at / phone_bind_required
-- 3) users_phone_e164_unique_idx
--
-- keep this migration id as a historical anchor for local-reset workflow.
