#!/usr/bin/env bash
set -euo pipefail

ROOT=""
CHECK_ONLY="false"

usage() {
  cat <<'USAGE'
用法:
  sync_claude_surface.sh [--root <repo-root>] [--check]

说明:
  - AGENTS.md 与 skills/* 是项目级真实来源。
  - 生成/校验 CLAUDE.md，使 Claude Code 入口镜像 AGENTS.md。
  - 将 .claude/skills/* 同步为指向根目录 skills/* 的相对软链接。
  - 只会自动移除指向 ../../skills/* 且源目录已不存在的旧软链接。
USAGE
}

resolve_root() {
  if [[ -n "$ROOT" ]]; then
    return
  fi
  if git rev-parse --show-toplevel >/dev/null 2>&1; then
    ROOT="$(git rev-parse --show-toplevel)"
  else
    ROOT="$(pwd)"
  fi
}

parse_args() {
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --root)
        ROOT="${2:-}"
        shift 2
        ;;
      --check)
        CHECK_ONLY="true"
        shift
        ;;
      -h|--help)
        usage
        exit 0
        ;;
      *)
        echo "未知参数: $1" >&2
        usage >&2
        exit 2
        ;;
    esac
  done
}

render_claude_md() {
  local out="$1"
  {
    cat <<'HEADER'
<!--
  Generated by scripts/harness/sync_claude_surface.sh.
  Do not edit CLAUDE.md manually; edit AGENTS.md and run the sync script.
-->

# CLAUDE.md

This file mirrors AGENTS.md for Claude Code. Project-level sources of truth:

1. AGENTS.md
2. skills/*

---

HEADER
    sed '1{/^# AGENTS\.md$/d;}' "$ROOT/AGENTS.md"
  } >"$out"
}

sync_claude_md() {
  local target="$ROOT/CLAUDE.md"
  local tmp
  tmp="$(mktemp)"
  render_claude_md "$tmp"

  if [[ "$CHECK_ONLY" == "true" ]]; then
    if [[ ! -f "$target" ]]; then
      echo "CLAUDE.md 缺失" >&2
      rm -f "$tmp"
      return 1
    fi
    if ! cmp -s "$tmp" "$target"; then
      echo "CLAUDE.md 未同步 AGENTS.md" >&2
      rm -f "$tmp"
      return 1
    fi
    rm -f "$tmp"
    return 0
  fi

  mv "$tmp" "$target"
}

is_managed_skill_link() {
  local path="$1"
  [[ -L "$path" ]] && [[ "$(readlink "$path")" == ../../skills/* ]]
}

sync_claude_skills() {
  local source_dir="$ROOT/skills"
  local target_dir="$ROOT/.claude/skills"
  local status=0

  if [[ ! -d "$source_dir" ]]; then
    echo "缺少根目录 skills/: $source_dir" >&2
    return 1
  fi

  if [[ "$CHECK_ONLY" != "true" ]]; then
    mkdir -p "$target_dir"
  elif [[ ! -d "$target_dir" ]]; then
    echo ".claude/skills 缺失" >&2
    return 1
  fi

  shopt -s nullglob
  local existing
  for existing in "$target_dir"/*; do
    if is_managed_skill_link "$existing"; then
      local existing_name
      existing_name="$(basename "$existing")"
      if [[ ! -d "$source_dir/$existing_name" ]]; then
        if [[ "$CHECK_ONLY" == "true" ]]; then
          echo ".claude/skills/$existing_name 是过期软链接" >&2
          status=1
        else
          rm "$existing"
        fi
      fi
    fi
  done

  local skill
  for skill in "$source_dir"/*; do
    [[ -d "$skill" ]] || continue
    local name
    name="$(basename "$skill")"
    local dest="$target_dir/$name"
    local desired="../../skills/$name"

    if [[ -L "$dest" ]]; then
      if [[ "$(readlink "$dest")" == "$desired" ]]; then
        continue
      fi
      if [[ "$CHECK_ONLY" == "true" ]]; then
        echo ".claude/skills/$name 指向错误: $(readlink "$dest")" >&2
        status=1
      else
        rm "$dest"
        ln -s "$desired" "$dest"
      fi
      continue
    fi

    if [[ -e "$dest" ]]; then
      echo ".claude/skills/$name 已存在但不是软链接，请先手动处理" >&2
      status=1
      continue
    fi

    if [[ "$CHECK_ONLY" == "true" ]]; then
      echo ".claude/skills/$name 缺失" >&2
      status=1
    else
      ln -s "$desired" "$dest"
    fi
  done

  return "$status"
}

main() {
  parse_args "$@"
  resolve_root
  sync_claude_md
  sync_claude_skills
  echo "Claude surface synced: CLAUDE.md + .claude/skills"
}

main "$@"
